-- AlterTable
ALTER TABLE "process_indicators" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "objetive" SET DATA TYPE VARCHAR,
ALTER COLUMN "periodicity" SET DATA TYPE VARCHAR,
ALTER COLUMN "in_charge" SET DATA TYPE VARCHAR;
